  <form method="post">
    <input type="hidden" value="{$result.0.id}"><br>
    <input type="text" value="{$result.0.schoolName}"><br>
    <input type="text" value="{$result.0.adress}"><br>
    <input type="text" value="{$result.0.adressNumber}"><br>
    <input type="text" value="{$result.0.adressExtra}"><br>
    <input type="text" value="{$result.0.zipcode}"><br>
    <input type="text" value="{$result.0.district}"><br>
    <input type="text" value="{$result.0.telnr}"><br>
    <input type="text" value="{$result.0.email}"><br>
    <input type="text" value="{$result.0.website}"><br>
    <input type="text" value="{$result.0.openDag1}"><br>
    <input type="text" value="{$result.0.openDag2}"><br>
    <input type="text" value="{$result.0.openDag3}"><br>
    <input type="text" value="{$result.0.openClass1}"><br>
    <input type="text" value="{$result.0.openClass2}"><br>
    <input type="text" value="{$result.0.openClass3}"><br>
    <input type="text" value="{$result.0.openClass4}"><br>
    <input type="text" value="{$result.0.openClass5}"><br>
    <input type="text" value="{$result.0.infoNight1}"><br>
    <input type="text" value="{$result.0.infoNight2}"><br>
    <input type="text" value="{$result.0.private}"><br>
    <input type="text" value="{$result.0.level}"><br>
    <input type="text" value="{$result.0.concept}"><br>
    <input type="text" value="{$result.0.specials}"><br>
    <input type="text" value="{$result.0.tto}"><br>
    <input type="text" value="{$result.0.sports}"><br>
    <input type="text" value="{$result.0.tech}"><br>
    <input type="text" value="{$result.0.spanish}"><br>
    <input type="text" value="{$result.0.vso}"><br>
    <input type="text" value="{$result.0.vmbob}"><br>
    <input type="text" value="{$result.0.vmbok}"><br>
    <input type="text" value="{$result.0.vmbot}"><br>
    <input type="text" value="{$result.0.havo}"><br>
    <input type="text" value="{$result.0.vwo}"><br>
    <input type="text" value="{$result.0.gymnasium}"><br>
    <input type="text" value="{$result.0.basis}"><br>
    <input type="text" value="{$result.0.art}"><br>
    <input type="submit" name="save_update" value="save">
  </form>
